version: "3"
services:
  backend-blog:
    image: liurenhao/backend-blog
    container_name: backend-blog
    hostname: backend-blog
    port: 8081:8081
    depends_on:
      - nginx
      - redis
      - mysql
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/www:/var/www
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    ports: 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql/
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports: 6479:6379
  env_file: .env
